import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#bfeaf4',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 28,
  },
  greetingBlock: {
    marginBottom: 10,
  },
  greetingText: {
    color: '#31506b',
    fontSize: 20,
    fontWeight: '800',
  },
  greetingPrompt: {
    color: '#123c69',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 30,
    marginTop: 2,
  },
  launchControls: {
    backgroundColor: '#dff6f2',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#87cfe1',
  },
  controlLabel: {
    color: '#123c69',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 7,
    textTransform: 'uppercase',
  },
  launchControlHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 7,
  },
  launchControlsRequired: {
    borderColor: '#87cfe1',
    backgroundColor: '#e8f8fb',
  },
  controlLabelRequired: {
    color: '#123c69',
    marginBottom: 0,
  },
  input: {
    borderColor: '#eadfce',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#fff',
    color: '#1f2937',
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cityInput: {
    flex: 1,
    borderColor: '#87cfe1',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#fff',
    color: '#123c69',
    fontWeight: '700',
  },
  cityInputRequired: {
    borderColor: '#123c69',
    borderWidth: 2,
  },
  locationButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#123c69',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 9,
  },
  filterIconButton: {
    backgroundColor: '#ff9f1c',
    borderColor: '#123c69',
    borderWidth: 2,
  },
  filterIconButtonActive: {
    backgroundColor: '#ff4b47',
  },
  filterGlyph: {
    height: 21,
    justifyContent: 'space-between',
    width: 22,
  },
  filterGlyphLine: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 3,
  },
  filterGlyphLineTop: {
    width: 18,
  },
  filterGlyphLineMiddle: {
    alignSelf: 'flex-end',
    width: 22,
  },
  filterGlyphLineBottom: {
    width: 14,
  },
  locationIcon: {
    width: 24,
    height: 24,
  },
  suggestionsList: {
    borderWidth: 1,
    borderColor: '#87cfe1',
    borderRadius: 8,
    backgroundColor: '#fff',
    overflow: 'hidden',
    marginBottom: 8,
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eadfce',
  },
  suggestionText: {
    color: '#1f2937',
    fontSize: 13,
  },
  emptyText: {
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 8,
  },
  filterSection: {
    marginTop: 0,
    marginBottom: 8,
  },
  filterPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#87cfe1',
    borderRadius: 8,
    backgroundColor: '#dff6f2',
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginBottom: 8,
    shadowColor: '#123c69',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 2,
  },
  filterPanel: {
    marginTop: 8,
  },
  filterTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#134e4a',
  },
  filterSummary: {
    marginTop: 2,
    color: '#31506b',
    fontSize: 12,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#87cfe1',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginBottom: 6,
  },
  dropdownLabel: {
    color: '#123c69',
    fontSize: 12,
    fontWeight: '800',
  },
  dropdownValue: {
    color: '#123c69',
    fontSize: 12,
    fontWeight: '900',
  },
  dropdownMenu: {
    borderWidth: 1,
    borderColor: '#87cfe1',
    borderRadius: 8,
    backgroundColor: '#fff',
    overflow: 'hidden',
    marginBottom: 8,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  dropdownItemSelected: {
    backgroundColor: '#123c69',
  },
  dropdownItemDisabled: {
    backgroundColor: '#f9fafb',
  },
  dropdownItemText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#123c69',
  },
  dropdownHelperText: {
    fontSize: 12,
    color: '#31506b',
  },
  dropdownItemTextDisabled: {
    color: '#a3a3a3',
  },
  dropdownItemTextSelected: {
    color: '#fff',
  },
  dropdownButtonDisabled: {
    opacity: 0.6,
  },
  tagInfo: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '900',
  },
  button: {
    backgroundColor: '#0f766e',
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: '#0f766e',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 3,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },
});
