export type Place = {
  own_review?: string;
  place_id: string;
  decision_id?: string;
  model?: string;
  structural_score?: number;
  ranking_components?: { interests: number; feedback: number; distance: number; local_policy: number; repeat: number };
  matched_interests?: string[];
  feedback_count?: number;
  score_components?: { confidence: number; socials: number; density: number; chain_multiplier: number };
  approximate_location?: boolean;
  needs_booking?: boolean;
  provider?: string;
  provider_place_id?: string;
  name: string;
  vicinity: string;
  types: string[];
  category?: 'food' | 'activity';
  tag_groups?: string[];
  explanation?: string;
  photo_url?: string;
  photo_attributions?: any[];
  rating?: number;
  relevance?: number;
  user_ratings_total?: number;
  price_level?: number;
  photos?: any[]; 
  likelihood?: number;
  latitude?: number;
  longitude?: number;
  distance_meters?: number;
  travel_times?: {
    walk_minutes?: number;
    drive_minutes?: number;
    transit_minutes?: number;
  };
};
